---
- name: Install pre reqs
  package:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - python-pip

- name: Add apt-key for docker
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: Add docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
    state: present